version: '3'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - ./docker-data/redis/data:/bitnami/redis/data
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: baruah
      POSTGRES_USER: arijeet
      POSTGRES_DB: MyBlog
    volumes:
      - .:/code
      - ./docker-data/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - MyBlog
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    networks:
      - MyBlog
  golang:
    build: ./docker-shared/golang
    environment:
      GR_DB_USERNAME: arijeet
      GR_DB_PASSWORD: baruah
      GR_DB_NAME: MyBlog
      GR_DB_DATA_SOURCE: "host=db user=arijeet password=baruah dbname=MyBlog sslmode=disable"
    depends_on:
      - db
      - redis
    volumes:
      - .:/go/src/github.com/ArijeetBaruah/MyBlog
    ports:
      - 80:9999
    networks:
      - MyBlog

networks:
  MyBlog:
    driver: bridge
