version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: local
      POSTGRES_DB: MyBlog
    volumes:
      - .:/code
      - ./docker-data/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - MyBlog
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    networks:
      - MyBlog
  golang:
    build: ./docker-shared/golang
    volumes:
      - .:/go/src/github.com/ArijeetBaruah/MyBlog
    ports:
      - 9999:9999
    networks:
      - MyBlog

networks:
  MyBlog:
    driver: bridge
